// Auto-generated by scripts/fetch-property-data.mjs — do not edit manually
// Source: LINZ NZ Street Address (data.linz.govt.nz:layer-105689)
// Generated: 2026-06-06

export interface PropertyAddress {
  id: string;
  fullAddress: string;
  streetName: string;
  streetNumber: string;
  coordinates: [number, number];
}

export interface PrecinctProperties {
  precinctId: string;
  name: string;
  count: number;
  addresses: PropertyAddress[];
}

export const PROPERTY_DATA: PrecinctProperties[] = [
  {
    "precinctId": "huri-street",
    "name": "Huri Street",
    "count": 67,
    "addresses": [
      {
        "id": "2364405",
        "fullAddress": "1 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "1",
        "coordinates": [
          -36.9494630209,
          174.7905339501
        ]
      },
      {
        "id": "2358375",
        "fullAddress": "10 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "10",
        "coordinates": [
          -36.9491245176,
          174.7909670079
        ]
      },
      {
        "id": "2364410",
        "fullAddress": "11 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "11",
        "coordinates": [
          -36.9496733064,
          174.7906259864
        ]
      },
      {
        "id": "2364437",
        "fullAddress": "12 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "12",
        "coordinates": [
          -36.9491250669,
          174.7910158641
        ]
      },
      {
        "id": "2364411",
        "fullAddress": "13 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "13",
        "coordinates": [
          -36.9493744797,
          174.7908892801
        ]
      },
      {
        "id": "2364438",
        "fullAddress": "14 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "14",
        "coordinates": [
          -36.9491270454,
          174.7910779875
        ]
      },
      {
        "id": "2364434",
        "fullAddress": "15 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "15",
        "coordinates": [
          -36.9494126651,
          174.7909201122
        ]
      },
      {
        "id": "2364439",
        "fullAddress": "16 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "16",
        "coordinates": [
          -36.9491511825,
          174.7911543557
        ]
      },
      {
        "id": "2364412",
        "fullAddress": "17 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "17",
        "coordinates": [
          -36.9494531183,
          174.7909341332
        ]
      },
      {
        "id": "2364440",
        "fullAddress": "18 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "18",
        "coordinates": [
          -36.949159492,
          174.7912085653
        ]
      },
      {
        "id": "2364413",
        "fullAddress": "19 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "19",
        "coordinates": [
          -36.9494886513,
          174.7909527735
        ]
      },
      {
        "id": "2364441",
        "fullAddress": "20 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "20",
        "coordinates": [
          -36.949165823,
          174.7912572352
        ]
      },
      {
        "id": "2364414",
        "fullAddress": "21 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "21",
        "coordinates": [
          -36.9495270968,
          174.7909638411
        ]
      },
      {
        "id": "2364442",
        "fullAddress": "22 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "22",
        "coordinates": [
          -36.9491725497,
          174.7913066965
        ]
      },
      {
        "id": "2364415",
        "fullAddress": "23 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "23",
        "coordinates": [
          -36.9495696199,
          174.790985394
        ]
      },
      {
        "id": "2364443",
        "fullAddress": "24 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "24",
        "coordinates": [
          -36.9491784851,
          174.7913537837
        ]
      },
      {
        "id": "2364416",
        "fullAddress": "25 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "25",
        "coordinates": [
          -36.9494507882,
          174.7910681101
        ]
      },
      {
        "id": "2364444",
        "fullAddress": "26 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "26",
        "coordinates": [
          -36.9491879817,
          174.7914060148
        ]
      },
      {
        "id": "2364417",
        "fullAddress": "27 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "27",
        "coordinates": [
          -36.9494583608,
          174.7911228659
        ]
      },
      {
        "id": "2364445",
        "fullAddress": "28 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "28",
        "coordinates": [
          -36.9492049037,
          174.7915220706
        ]
      },
      {
        "id": "2364418",
        "fullAddress": "29 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "29",
        "coordinates": [
          -36.9494601084,
          174.7911741266
        ]
      },
      {
        "id": "2364406",
        "fullAddress": "3 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "3",
        "coordinates": [
          -36.949507874,
          174.7905467653
        ]
      },
      {
        "id": "2364446",
        "fullAddress": "30 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "30",
        "coordinates": [
          -36.9492135402,
          174.7915772114
        ]
      },
      {
        "id": "2364419",
        "fullAddress": "31 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "31",
        "coordinates": [
          -36.9494624384,
          174.7912195622
        ]
      },
      {
        "id": "2364447",
        "fullAddress": "32 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "32",
        "coordinates": [
          -36.949220848,
          174.791626041
        ]
      },
      {
        "id": "2364420",
        "fullAddress": "33 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "33",
        "coordinates": [
          -36.9494670985,
          174.7912714055
        ]
      },
      {
        "id": "2364448",
        "fullAddress": "34 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "34",
        "coordinates": [
          -36.9492274915,
          174.7916752027
        ]
      },
      {
        "id": "2364423",
        "fullAddress": "35 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "35",
        "coordinates": [
          -36.9494717585,
          174.7913191711
        ]
      },
      {
        "id": "2364449",
        "fullAddress": "36 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "36",
        "coordinates": [
          -36.9492367924,
          174.7917276862
        ]
      },
      {
        "id": "2364425",
        "fullAddress": "37 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "37",
        "coordinates": [
          -36.9494828262,
          174.7913745094
        ]
      },
      {
        "id": "2364450",
        "fullAddress": "38 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "38",
        "coordinates": [
          -36.9492866185,
          174.7918432828
        ]
      },
      {
        "id": "2364427",
        "fullAddress": "39 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "39",
        "coordinates": [
          -36.9494903988,
          174.7914409154
        ]
      },
      {
        "id": "2364451",
        "fullAddress": "40 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "40",
        "coordinates": [
          -36.9492401141,
          174.7918598915
        ]
      },
      {
        "id": "2364429",
        "fullAddress": "41 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "41",
        "coordinates": [
          -36.9495020489,
          174.7914945061
        ]
      },
      {
        "id": "2364452",
        "fullAddress": "42 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "42",
        "coordinates": [
          -36.9492022463,
          174.7918725141
        ]
      },
      {
        "id": "2364430",
        "fullAddress": "43 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "43",
        "coordinates": [
          -36.949507874,
          174.7915446018
        ]
      },
      {
        "id": "2364453",
        "fullAddress": "44 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "44",
        "coordinates": [
          -36.9491637141,
          174.7918844723
        ]
      },
      {
        "id": "2364431",
        "fullAddress": "45 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "45",
        "coordinates": [
          -36.9495154466,
          174.7915935325
        ]
      },
      {
        "id": "2364454",
        "fullAddress": "46 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "46",
        "coordinates": [
          -36.9491192028,
          174.7918964306
        ]
      },
      {
        "id": "2364432",
        "fullAddress": "47 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "47",
        "coordinates": [
          -36.9495189417,
          174.7916418807
        ]
      },
      {
        "id": "2364455",
        "fullAddress": "48 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "48",
        "coordinates": [
          -36.9490667193,
          174.7919097176
        ]
      },
      {
        "id": "2364433",
        "fullAddress": "49 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "49",
        "coordinates": [
          -36.9495259318,
          174.791697219
        ]
      },
      {
        "id": "2364407",
        "fullAddress": "5 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "5",
        "coordinates": [
          -36.9495451545,
          174.7905706481
        ]
      },
      {
        "id": "2364456",
        "fullAddress": "50 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "50",
        "coordinates": [
          -36.9490195506,
          174.7919223402
        ]
      },
      {
        "id": "2358377",
        "fullAddress": "51 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "51",
        "coordinates": [
          -36.94951407,
          174.7918871572
        ]
      },
      {
        "id": "2364457",
        "fullAddress": "52 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "52",
        "coordinates": [
          -36.9489810184,
          174.791931641
        ]
      },
      {
        "id": "2358378",
        "fullAddress": "53 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "53",
        "coordinates": [
          -36.9495574989,
          174.791895843
        ]
      },
      {
        "id": "2364458",
        "fullAddress": "54 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "54",
        "coordinates": [
          -36.9489358428,
          174.7919402776
        ]
      },
      {
        "id": "2358379",
        "fullAddress": "55 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "55",
        "coordinates": [
          -36.9495947237,
          174.7919008063
        ]
      },
      {
        "id": "2358380",
        "fullAddress": "57 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "57",
        "coordinates": [
          -36.9496369118,
          174.7919132146
        ]
      },
      {
        "id": "2358381",
        "fullAddress": "59 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "59",
        "coordinates": [
          -36.9496753774,
          174.7919231412
        ]
      },
      {
        "id": "2364435",
        "fullAddress": "6 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "6",
        "coordinates": [
          -36.9491341678,
          174.7908611491
        ]
      },
      {
        "id": "2358382",
        "fullAddress": "61 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "61",
        "coordinates": [
          -36.9497113614,
          174.7919380311
        ]
      },
      {
        "id": "2358383",
        "fullAddress": "63 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "63",
        "coordinates": [
          -36.9497510678,
          174.7919554027
        ]
      },
      {
        "id": "2358384",
        "fullAddress": "65 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "65",
        "coordinates": [
          -36.9497833293,
          174.7919901458
        ]
      },
      {
        "id": "2358385",
        "fullAddress": "67 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "67",
        "coordinates": [
          -36.9498267582,
          174.7920273706
        ]
      },
      {
        "id": "2358386",
        "fullAddress": "69 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "69",
        "coordinates": [
          -36.9493304278,
          174.7922147353
        ]
      },
      {
        "id": "2364408",
        "fullAddress": "7 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "7",
        "coordinates": [
          -36.9495853476,
          174.7905875409
        ]
      },
      {
        "id": "2358387",
        "fullAddress": "71 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "71",
        "coordinates": [
          -36.9492944438,
          174.792230866
        ]
      },
      {
        "id": "2358388",
        "fullAddress": "73 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "73",
        "coordinates": [
          -36.9492534966,
          174.7922432743
        ]
      },
      {
        "id": "2358389",
        "fullAddress": "75 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "75",
        "coordinates": [
          -36.9492162718,
          174.7922457559
        ]
      },
      {
        "id": "2358390",
        "fullAddress": "77 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "77",
        "coordinates": [
          -36.9491765654,
          174.792259405
        ]
      },
      {
        "id": "2358391",
        "fullAddress": "79 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "79",
        "coordinates": [
          -36.9491380998,
          174.7922618867
        ]
      },
      {
        "id": "2364436",
        "fullAddress": "8 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "8",
        "coordinates": [
          -36.9491270454,
          174.7909161501
        ]
      },
      {
        "id": "2358392",
        "fullAddress": "81 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "81",
        "coordinates": [
          -36.9490971525,
          174.7922792582
        ]
      },
      {
        "id": "2358393",
        "fullAddress": "83 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "83",
        "coordinates": [
          -36.9490140172,
          174.7922370702
        ]
      },
      {
        "id": "2364409",
        "fullAddress": "9 Huri Street, Māngere Bridge, Auckland",
        "streetName": "Huri Street",
        "streetNumber": "9",
        "coordinates": [
          -36.9496255407,
          174.790600356
        ]
      }
    ]
  },
  {
    "precinctId": "tukari-lane",
    "name": "Tukari Lane",
    "count": 61,
    "addresses": [
      {
        "id": "2364755",
        "fullAddress": "1 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "1",
        "coordinates": [
          -36.9491807111,
          174.7907469369
        ]
      },
      {
        "id": "2364743",
        "fullAddress": "10 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "10",
        "coordinates": [
          -36.949074481,
          174.7903566172
        ]
      },
      {
        "id": "2364760",
        "fullAddress": "11 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "11",
        "coordinates": [
          -36.9489973883,
          174.7908628795
        ]
      },
      {
        "id": "2364744",
        "fullAddress": "12 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "12",
        "coordinates": [
          -36.949031382,
          174.7903371923
        ]
      },
      {
        "id": "2364761",
        "fullAddress": "13 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "13",
        "coordinates": [
          -36.9489840337,
          174.7909090137
        ]
      },
      {
        "id": "2364745",
        "fullAddress": "14 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "14",
        "coordinates": [
          -36.9489421487,
          174.7902461379
        ]
      },
      {
        "id": "2364762",
        "fullAddress": "15 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "15",
        "coordinates": [
          -36.948970072,
          174.7909551479
        ]
      },
      {
        "id": "2364746",
        "fullAddress": "16 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "16",
        "coordinates": [
          -36.9489245448,
          174.7903074478
        ]
      },
      {
        "id": "2364763",
        "fullAddress": "17 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "17",
        "coordinates": [
          -36.9489585385,
          174.7910018892
        ]
      },
      {
        "id": "2364747",
        "fullAddress": "18 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "18",
        "coordinates": [
          -36.9489105832,
          174.790352368
        ]
      },
      {
        "id": "2364764",
        "fullAddress": "19 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "19",
        "coordinates": [
          -36.9489463979,
          174.7910492374
        ]
      },
      {
        "id": "2364739",
        "fullAddress": "2 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "2",
        "coordinates": [
          -36.9492353438,
          174.7904343169
        ]
      },
      {
        "id": "2364748",
        "fullAddress": "20 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "20",
        "coordinates": [
          -36.9488948004,
          174.7904063936
        ]
      },
      {
        "id": "2364765",
        "fullAddress": "21 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "21",
        "coordinates": [
          -36.948928794,
          174.7910971928
        ]
      },
      {
        "id": "2364749",
        "fullAddress": "22 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "22",
        "coordinates": [
          -36.9488820528,
          174.7904664895
        ]
      },
      {
        "id": "2364794",
        "fullAddress": "23 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "23",
        "coordinates": [
          -36.9488620208,
          174.7912665539
        ]
      },
      {
        "id": "2364750",
        "fullAddress": "24 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "24",
        "coordinates": [
          -36.9488668771,
          174.7905229432
        ]
      },
      {
        "id": "2364795",
        "fullAddress": "25 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "25",
        "coordinates": [
          -36.9488529154,
          174.7913284709
        ]
      },
      {
        "id": "2364751",
        "fullAddress": "26 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "26",
        "coordinates": [
          -36.9488517013,
          174.7905678633
        ]
      },
      {
        "id": "2364796",
        "fullAddress": "27 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "27",
        "coordinates": [
          -36.9488529154,
          174.7913794613
        ]
      },
      {
        "id": "2364752",
        "fullAddress": "28 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "28",
        "coordinates": [
          -36.9488383467,
          174.7906152116
        ]
      },
      {
        "id": "2364797",
        "fullAddress": "29 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "29",
        "coordinates": [
          -36.9488608068,
          174.7914274166
        ]
      },
      {
        "id": "2364756",
        "fullAddress": "3 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "3",
        "coordinates": [
          -36.9491376121,
          174.7907354034
        ]
      },
      {
        "id": "2364753",
        "fullAddress": "30 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "30",
        "coordinates": [
          -36.9488255991,
          174.7906607388
        ]
      },
      {
        "id": "2364798",
        "fullAddress": "31 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "31",
        "coordinates": [
          -36.9488693052,
          174.7914759789
        ]
      },
      {
        "id": "2364754",
        "fullAddress": "32 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "32",
        "coordinates": [
          -36.9488086023,
          174.7907147644
        ]
      },
      {
        "id": "2364799",
        "fullAddress": "33 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "33",
        "coordinates": [
          -36.9488765895,
          174.7915312186
        ]
      },
      {
        "id": "2364766",
        "fullAddress": "34 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "34",
        "coordinates": [
          -36.9486878035,
          174.7911251161
        ]
      },
      {
        "id": "2364800",
        "fullAddress": "35 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "35",
        "coordinates": [
          -36.948886909,
          174.7915919215
        ]
      },
      {
        "id": "2364767",
        "fullAddress": "36 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "36",
        "coordinates": [
          -36.9486714137,
          174.7911803557
        ]
      },
      {
        "id": "2364801",
        "fullAddress": "37 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "37",
        "coordinates": [
          -36.9488948004,
          174.7916489822
        ]
      },
      {
        "id": "2364768",
        "fullAddress": "38 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "38",
        "coordinates": [
          -36.948656845,
          174.7912252759
        ]
      },
      {
        "id": "2364787",
        "fullAddress": "39 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "39",
        "coordinates": [
          -36.9489026918,
          174.7916975446
        ]
      },
      {
        "id": "2364740",
        "fullAddress": "4 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "4",
        "coordinates": [
          -36.9491928517,
          174.7904124639
        ]
      },
      {
        "id": "2364769",
        "fullAddress": "40 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "40",
        "coordinates": [
          -36.9486349919,
          174.7912853718
        ]
      },
      {
        "id": "2364786",
        "fullAddress": "41 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "41",
        "coordinates": [
          -36.9489093691,
          174.7917461069
        ]
      },
      {
        "id": "2364770",
        "fullAddress": "42 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "42",
        "coordinates": [
          -36.9486198162,
          174.7913685348
        ]
      },
      {
        "id": "2364785",
        "fullAddress": "43 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "43",
        "coordinates": [
          -36.9489178675,
          174.7917977044
        ]
      },
      {
        "id": "2364771",
        "fullAddress": "44 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "44",
        "coordinates": [
          -36.9486258865,
          174.7914286307
        ]
      },
      {
        "id": "2364790",
        "fullAddress": "46 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "46",
        "coordinates": [
          -36.9486331708,
          174.7914796211
        ]
      },
      {
        "id": "2364791",
        "fullAddress": "48 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "48",
        "coordinates": [
          -36.9486404552,
          174.7915275764
        ]
      },
      {
        "id": "2364757",
        "fullAddress": "5 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "5",
        "coordinates": [
          -36.9490993692,
          174.7907214417
        ]
      },
      {
        "id": "2364792",
        "fullAddress": "50 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "50",
        "coordinates": [
          -36.9486489536,
          174.7915761387
        ]
      },
      {
        "id": "2364793",
        "fullAddress": "52 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "52",
        "coordinates": [
          -36.948656845,
          174.7916325925
        ]
      },
      {
        "id": "2364784",
        "fullAddress": "54 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "54",
        "coordinates": [
          -36.9486659504,
          174.7916963305
        ]
      },
      {
        "id": "2364783",
        "fullAddress": "56 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "56",
        "coordinates": [
          -36.9486744488,
          174.7917558194
        ]
      },
      {
        "id": "2364782",
        "fullAddress": "58 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "58",
        "coordinates": [
          -36.9486817332,
          174.7918019536
        ]
      },
      {
        "id": "2364741",
        "fullAddress": "6 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "6",
        "coordinates": [
          -36.9491533948,
          174.7903930389
        ]
      },
      {
        "id": "2364781",
        "fullAddress": "60 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "60",
        "coordinates": [
          -36.9486914456,
          174.7918511229
        ]
      },
      {
        "id": "2364780",
        "fullAddress": "62 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "62",
        "coordinates": [
          -36.9486975159,
          174.7919008993
        ]
      },
      {
        "id": "2364779",
        "fullAddress": "64 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "64",
        "coordinates": [
          -36.9487060143,
          174.7919537109
        ]
      },
      {
        "id": "2364778",
        "fullAddress": "66 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "66",
        "coordinates": [
          -36.9487132987,
          174.7920223052
        ]
      },
      {
        "id": "2364777",
        "fullAddress": "68 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "68",
        "coordinates": [
          -36.9487230112,
          174.7920781518
        ]
      },
      {
        "id": "2364758",
        "fullAddress": "7 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "7",
        "coordinates": [
          -36.9490544491,
          174.7907080871
        ]
      },
      {
        "id": "2364776",
        "fullAddress": "70 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "70",
        "coordinates": [
          -36.9487302955,
          174.7921273212
        ]
      },
      {
        "id": "2364775",
        "fullAddress": "72 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "72",
        "coordinates": [
          -36.9487363658,
          174.7921752765
        ]
      },
      {
        "id": "2364774",
        "fullAddress": "74 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "74",
        "coordinates": [
          -36.9487472923,
          174.7922232318
        ]
      },
      {
        "id": "2364773",
        "fullAddress": "76 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "76",
        "coordinates": [
          -36.9487551837,
          174.7922711871
        ]
      },
      {
        "id": "2364772",
        "fullAddress": "78 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "78",
        "coordinates": [
          -36.9487709665,
          174.7923428166
        ]
      },
      {
        "id": "2364742",
        "fullAddress": "8 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "8",
        "coordinates": [
          -36.9491139379,
          174.7903754351
        ]
      },
      {
        "id": "2364759",
        "fullAddress": "9 Tukari Lane, Māngere Bridge, Auckland",
        "streetName": "Tukari Lane",
        "streetNumber": "9",
        "coordinates": [
          -36.9490125641,
          174.790810675
        ]
      }
    ]
  },
  {
    "precinctId": "tima-lane",
    "name": "Tima Lane",
    "count": 59,
    "addresses": [
      {
        "id": "2358559",
        "fullAddress": "1 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "1",
        "coordinates": [
          -36.9495106268,
          174.792234763
        ]
      },
      {
        "id": "2358571",
        "fullAddress": "10 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "10",
        "coordinates": [
          -36.9493358577,
          174.7925051089
        ]
      },
      {
        "id": "2358564",
        "fullAddress": "11 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "11",
        "coordinates": [
          -36.9497227163,
          174.792277545
        ]
      },
      {
        "id": "2358572",
        "fullAddress": "12 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "12",
        "coordinates": [
          -36.9493449602,
          174.7925679165
        ]
      },
      {
        "id": "2358565",
        "fullAddress": "13 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "13",
        "coordinates": [
          -36.9497664086,
          174.792281186
        ]
      },
      {
        "id": "2358573",
        "fullAddress": "14 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "14",
        "coordinates": [
          -36.9493522423,
          174.7926461985
        ]
      },
      {
        "id": "2358566",
        "fullAddress": "15 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "15",
        "coordinates": [
          -36.9498192034,
          174.7922638912
        ]
      },
      {
        "id": "2358574",
        "fullAddress": "16 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "16",
        "coordinates": [
          -36.9493367679,
          174.7926953523
        ]
      },
      {
        "id": "2358580",
        "fullAddress": "17 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "17",
        "coordinates": [
          -36.9494915114,
          174.793296121
        ]
      },
      {
        "id": "2358575",
        "fullAddress": "18 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "18",
        "coordinates": [
          -36.9493249346,
          174.7927408651
        ]
      },
      {
        "id": "2358581",
        "fullAddress": "19 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "19",
        "coordinates": [
          -36.9494423576,
          174.7932879287
        ]
      },
      {
        "id": "2358567",
        "fullAddress": "2 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "2",
        "coordinates": [
          -36.9493813705,
          174.7922101861
        ]
      },
      {
        "id": "2358576",
        "fullAddress": "20 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "20",
        "coordinates": [
          -36.9492885244,
          174.7928737624
        ]
      },
      {
        "id": "2358582",
        "fullAddress": "21 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "21",
        "coordinates": [
          -36.9494068576,
          174.7932797364
        ]
      },
      {
        "id": "2358577",
        "fullAddress": "22 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "22",
        "coordinates": [
          -36.9492402808,
          174.7929028906
        ]
      },
      {
        "id": "2358583",
        "fullAddress": "23 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "23",
        "coordinates": [
          -36.9493668064,
          174.7932733646
        ]
      },
      {
        "id": "2358578",
        "fullAddress": "24 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "24",
        "coordinates": [
          -36.9492293578,
          174.7929565957
        ]
      },
      {
        "id": "2358584",
        "fullAddress": "25 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "25",
        "coordinates": [
          -36.9493303962,
          174.7932633518
        ]
      },
      {
        "id": "2358579",
        "fullAddress": "26 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "26",
        "coordinates": [
          -36.949219345,
          174.7930030187
        ]
      },
      {
        "id": "2358585",
        "fullAddress": "27 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "27",
        "coordinates": [
          -36.9492885244,
          174.7932451467
        ]
      },
      {
        "id": "2358614",
        "fullAddress": "28 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "28",
        "coordinates": [
          -36.9490919092,
          174.7929493136
        ]
      },
      {
        "id": "2358586",
        "fullAddress": "29 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "29",
        "coordinates": [
          -36.9492384603,
          174.7932324031
        ]
      },
      {
        "id": "2358560",
        "fullAddress": "3 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "3",
        "coordinates": [
          -36.9495561395,
          174.792238404
        ]
      },
      {
        "id": "2358615",
        "fullAddress": "30 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "30",
        "coordinates": [
          -36.9490809861,
          174.7928874162
        ]
      },
      {
        "id": "2358587",
        "fullAddress": "31 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "31",
        "coordinates": [
          -36.9491947681,
          174.7932169288
        ]
      },
      {
        "id": "2358616",
        "fullAddress": "32 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "32",
        "coordinates": [
          -36.9490746143,
          174.7928355317
        ]
      },
      {
        "id": "2358588",
        "fullAddress": "33 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "33",
        "coordinates": [
          -36.9491565373,
          174.7932005442
        ]
      },
      {
        "id": "2358617",
        "fullAddress": "34 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "34",
        "coordinates": [
          -36.9490691528,
          174.7927854676
        ]
      },
      {
        "id": "2358589",
        "fullAddress": "35 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "35",
        "coordinates": [
          -36.9491164861,
          174.7931868903
        ]
      },
      {
        "id": "2358618",
        "fullAddress": "36 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "36",
        "coordinates": [
          -36.9490609605,
          174.7927372241
        ]
      },
      {
        "id": "2358590",
        "fullAddress": "37 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "37",
        "coordinates": [
          -36.9490809861,
          174.7931768775
        ]
      },
      {
        "id": "2358619",
        "fullAddress": "38 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "38",
        "coordinates": [
          -36.9490536785,
          174.7926889805
        ]
      },
      {
        "id": "2358591",
        "fullAddress": "39 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "39",
        "coordinates": [
          -36.9490363836,
          174.7931659545
        ]
      },
      {
        "id": "2358568",
        "fullAddress": "4 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "4",
        "coordinates": [
          -36.9493103705,
          174.7923530962
        ]
      },
      {
        "id": "2358620",
        "fullAddress": "40 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "40",
        "coordinates": [
          -36.9490463964,
          174.7926389165
        ]
      },
      {
        "id": "2358592",
        "fullAddress": "41 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "41",
        "coordinates": [
          -36.9490008836,
          174.7931468391
        ]
      },
      {
        "id": "2358621",
        "fullAddress": "42 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "42",
        "coordinates": [
          -36.9490300118,
          174.7925560832
        ]
      },
      {
        "id": "2358593",
        "fullAddress": "43 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "43",
        "coordinates": [
          -36.9489517298,
          174.793128634
        ]
      },
      {
        "id": "2358622",
        "fullAddress": "44 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "44",
        "coordinates": [
          -36.949019999,
          174.7924950961
        ]
      },
      {
        "id": "2358594",
        "fullAddress": "45 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "45",
        "coordinates": [
          -36.9488679863,
          174.7929829931
        ]
      },
      {
        "id": "2358623",
        "fullAddress": "46 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "46",
        "coordinates": [
          -36.9490136272,
          174.7924477628
        ]
      },
      {
        "id": "2358595",
        "fullAddress": "47 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "47",
        "coordinates": [
          -36.9488607043,
          174.7929283777
        ]
      },
      {
        "id": "2358624",
        "fullAddress": "48 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "48",
        "coordinates": [
          -36.9490090759,
          174.7924004295
        ]
      },
      {
        "id": "2358596",
        "fullAddress": "49 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "49",
        "coordinates": [
          -36.948852512,
          174.7928801342
        ]
      },
      {
        "id": "2358561",
        "fullAddress": "5 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "5",
        "coordinates": [
          -36.949597101,
          174.7922566091
        ]
      },
      {
        "id": "2358625",
        "fullAddress": "50 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "50",
        "coordinates": [
          -36.9489990631,
          174.7923549167
        ]
      },
      {
        "id": "2358609",
        "fullAddress": "51 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "51",
        "coordinates": [
          -36.9488452299,
          174.7928291599
        ]
      },
      {
        "id": "2358626",
        "fullAddress": "52 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "52",
        "coordinates": [
          -36.9489917811,
          174.7923048527
        ]
      },
      {
        "id": "2358598",
        "fullAddress": "53 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "53",
        "coordinates": [
          -36.9488361274,
          174.7927800061
        ]
      },
      {
        "id": "2358599",
        "fullAddress": "55 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "55",
        "coordinates": [
          -36.9488279351,
          174.7927235702
        ]
      },
      {
        "id": "2358597",
        "fullAddress": "57 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "57",
        "coordinates": [
          -36.948817012,
          174.7926580318
        ]
      },
      {
        "id": "2358610",
        "fullAddress": "59 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "59",
        "coordinates": [
          -36.9488079094,
          174.7925997755
        ]
      },
      {
        "id": "2358569",
        "fullAddress": "6 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "6",
        "coordinates": [
          -36.9493212936,
          174.792405891
        ]
      },
      {
        "id": "2358611",
        "fullAddress": "61 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "61",
        "coordinates": [
          -36.9488015377,
          174.792555173
        ]
      },
      {
        "id": "2358612",
        "fullAddress": "63 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "63",
        "coordinates": [
          -36.9487951659,
          174.7925069294
        ]
      },
      {
        "id": "2358613",
        "fullAddress": "65 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "65",
        "coordinates": [
          -36.9487851531,
          174.792441391
        ]
      },
      {
        "id": "2358562",
        "fullAddress": "7 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "7",
        "coordinates": [
          -36.9496389728,
          174.792270263
        ]
      },
      {
        "id": "2358570",
        "fullAddress": "8 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "8",
        "coordinates": [
          -36.9493249346,
          174.7924495833
        ]
      },
      {
        "id": "2358563",
        "fullAddress": "9 Tima Lane, Māngere Bridge, Auckland",
        "streetName": "Tima Lane",
        "streetNumber": "9",
        "coordinates": [
          -36.9496817548,
          174.7922784553
        ]
      }
    ]
  },
  {
    "precinctId": "whai-hua-lane",
    "name": "Whai Hua Lane",
    "count": 40,
    "addresses": [
      {
        "id": "2327566",
        "fullAddress": "10 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "10",
        "coordinates": [
          -36.9503491956,
          174.7926904552
        ]
      },
      {
        "id": "2327567",
        "fullAddress": "12 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "12",
        "coordinates": [
          -36.9503313471,
          174.7927432868
        ]
      },
      {
        "id": "2009140",
        "fullAddress": "13 Tanners Road, Māngere Bridge, Auckland",
        "streetName": "Tanners Road",
        "streetNumber": "13",
        "coordinates": [
          -36.95052205,
          174.7924159167
        ]
      },
      {
        "id": "2327568",
        "fullAddress": "14 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "14",
        "coordinates": [
          -36.9503134986,
          174.7928039718
        ]
      },
      {
        "id": "2327569",
        "fullAddress": "16 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "16",
        "coordinates": [
          -36.9502970779,
          174.7928532337
        ]
      },
      {
        "id": "2327570",
        "fullAddress": "18 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "18",
        "coordinates": [
          -36.9502835131,
          174.7929003537
        ]
      },
      {
        "id": "2327578",
        "fullAddress": "19 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "19",
        "coordinates": [
          -36.9504420079,
          174.7930445697
        ]
      },
      {
        "id": "2327562",
        "fullAddress": "2 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "2",
        "coordinates": [
          -36.950404883,
          174.792500547
        ]
      },
      {
        "id": "2327571",
        "fullAddress": "20 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "20",
        "coordinates": [
          -36.9502663785,
          174.7929546132
        ]
      },
      {
        "id": "2327579",
        "fullAddress": "21 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "21",
        "coordinates": [
          -36.9504441497,
          174.7931031129
        ]
      },
      {
        "id": "2327572",
        "fullAddress": "22 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "22",
        "coordinates": [
          -36.950212119,
          174.7929967357
        ]
      },
      {
        "id": "2327580",
        "fullAddress": "23 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "23",
        "coordinates": [
          -36.9504484333,
          174.7931480911
        ]
      },
      {
        "id": "2327573",
        "fullAddress": "24 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "24",
        "coordinates": [
          -36.9501942705,
          174.7930467115
        ]
      },
      {
        "id": "2327581",
        "fullAddress": "25 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "25",
        "coordinates": [
          -36.9504512891,
          174.7932030645
        ]
      },
      {
        "id": "2327574",
        "fullAddress": "26 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "26",
        "coordinates": [
          -36.9501771359,
          174.7930938316
        ]
      },
      {
        "id": "2327582",
        "fullAddress": "27 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "27",
        "coordinates": [
          -36.9504577146,
          174.7932487567
        ]
      },
      {
        "id": "2327575",
        "fullAddress": "28 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "28",
        "coordinates": [
          -36.950163571,
          174.793137382
        ]
      },
      {
        "id": "2327583",
        "fullAddress": "29 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "29",
        "coordinates": [
          -36.9504669958,
          174.7932973047
        ]
      },
      {
        "id": "2327576",
        "fullAddress": "30 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "30",
        "coordinates": [
          -36.9501378692,
          174.7931773627
        ]
      },
      {
        "id": "2327584",
        "fullAddress": "31 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "31",
        "coordinates": [
          -36.9504712794,
          174.7933558478
        ]
      },
      {
        "id": "2327577",
        "fullAddress": "32 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "32",
        "coordinates": [
          -36.9501193067,
          174.7932287664
        ]
      },
      {
        "id": "2327585",
        "fullAddress": "33 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "33",
        "coordinates": [
          -36.9504827025,
          174.7934122491
        ]
      },
      {
        "id": "2327586",
        "fullAddress": "35 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "35",
        "coordinates": [
          -36.9504976952,
          174.7934686504
        ]
      },
      {
        "id": "2327587",
        "fullAddress": "37 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "37",
        "coordinates": [
          -36.9505019789,
          174.7935193402
        ]
      },
      {
        "id": "2327588",
        "fullAddress": "39 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "39",
        "coordinates": [
          -36.9505105462,
          174.7935664603
        ]
      },
      {
        "id": "2327563",
        "fullAddress": "4 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "4",
        "coordinates": [
          -36.9503891763,
          174.7925526647
        ]
      },
      {
        "id": "2327589",
        "fullAddress": "41 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "41",
        "coordinates": [
          -36.9505134019,
          174.7936157222
        ]
      },
      {
        "id": "2327590",
        "fullAddress": "43 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "43",
        "coordinates": [
          -36.9505291086,
          174.7936971114
        ]
      },
      {
        "id": "2327591",
        "fullAddress": "45 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "45",
        "coordinates": [
          -36.9503877484,
          174.793641424
        ]
      },
      {
        "id": "2327592",
        "fullAddress": "47 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "47",
        "coordinates": [
          -36.9503477677,
          174.7935607488
        ]
      },
      {
        "id": "2327593",
        "fullAddress": "49 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "49",
        "coordinates": [
          -36.9503099289,
          174.7935443281
        ]
      },
      {
        "id": "2327594",
        "fullAddress": "51 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "51",
        "coordinates": [
          -36.950260667,
          174.7935557512
        ]
      },
      {
        "id": "2327595",
        "fullAddress": "53 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "53",
        "coordinates": [
          -36.9502128329,
          174.7935478978
        ]
      },
      {
        "id": "2327597",
        "fullAddress": "55 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "55",
        "coordinates": [
          -36.9501678547,
          174.7935314772
        ]
      },
      {
        "id": "2327598",
        "fullAddress": "57 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "57",
        "coordinates": [
          -36.9501293019,
          174.7935179123
        ]
      },
      {
        "id": "2327599",
        "fullAddress": "59 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "59",
        "coordinates": [
          -36.9500907491,
          174.7935036335
        ]
      },
      {
        "id": "2327564",
        "fullAddress": "6 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "6",
        "coordinates": [
          -36.9503748975,
          174.792596929
        ]
      },
      {
        "id": "2327600",
        "fullAddress": "61 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "61",
        "coordinates": [
          -36.950055766,
          174.7934893547
        ]
      },
      {
        "id": "2327601",
        "fullAddress": "63 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "63",
        "coordinates": [
          -36.9500129296,
          174.7934722201
        ]
      },
      {
        "id": "2327565",
        "fullAddress": "8 Whai Hua Lane, Māngere Bridge, Auckland",
        "streetName": "Whai Hua Lane",
        "streetNumber": "8",
        "coordinates": [
          -36.9503599047,
          174.7926440491
        ]
      }
    ]
  },
  {
    "precinctId": "tanners-rd",
    "name": "Tanners Rd",
    "count": 7,
    "addresses": [
      {
        "id": "2009187",
        "fullAddress": "22 Tanners Road, Māngere Bridge, Auckland",
        "streetName": "Tanners Road",
        "streetNumber": "22",
        "coordinates": [
          -36.9503086167,
          174.7919783667
        ]
      },
      {
        "id": "2009188",
        "fullAddress": "24 Tanners Road, Māngere Bridge, Auckland",
        "streetName": "Tanners Road",
        "streetNumber": "24",
        "coordinates": [
          -36.95027745,
          174.79209865
        ]
      },
      {
        "id": "2009189",
        "fullAddress": "26 Tanners Road, Māngere Bridge, Auckland",
        "streetName": "Tanners Road",
        "streetNumber": "26",
        "coordinates": [
          -36.9502494667,
          174.7921651333
        ]
      },
      {
        "id": "2009186",
        "fullAddress": "31 Tanners Road, Māngere Bridge, Auckland",
        "streetName": "Tanners Road",
        "streetNumber": "31",
        "coordinates": [
          -36.9502630833,
          174.7926014833
        ]
      },
      {
        "id": "2009185",
        "fullAddress": "33 Tanners Road, Māngere Bridge, Auckland",
        "streetName": "Tanners Road",
        "streetNumber": "33",
        "coordinates": [
          -36.9501988833,
          174.79257375
        ]
      },
      {
        "id": "2009184",
        "fullAddress": "35 Tanners Road, Māngere Bridge, Auckland",
        "streetName": "Tanners Road",
        "streetNumber": "35",
        "coordinates": [
          -36.9501418,
          174.7925476
        ]
      },
      {
        "id": "2009183",
        "fullAddress": "37 Tanners Road, Māngere Bridge, Auckland",
        "streetName": "Tanners Road",
        "streetNumber": "37",
        "coordinates": [
          -36.950062,
          174.7925110333
        ]
      }
    ]
  },
  {
    "precinctId": "mikoikoi-cres",
    "name": "Mikoikoi Cres",
    "count": 4,
    "addresses": [
      {
        "id": "2009182",
        "fullAddress": "1 Mikoikoi Crescent, Māngere Bridge, Auckland",
        "streetName": "Mikoikoi Crescent",
        "streetNumber": "1",
        "coordinates": [
          -36.9499834,
          174.7924645333
        ]
      },
      {
        "id": "2009181",
        "fullAddress": "3 Mikoikoi Crescent, Māngere Bridge, Auckland",
        "streetName": "Mikoikoi Crescent",
        "streetNumber": "3",
        "coordinates": [
          -36.9499396667,
          174.7925470833
        ]
      },
      {
        "id": "2009180",
        "fullAddress": "5 Mikoikoi Crescent, Māngere Bridge, Auckland",
        "streetName": "Mikoikoi Crescent",
        "streetNumber": "5",
        "coordinates": [
          -36.9498811167,
          174.7925696833
        ]
      },
      {
        "id": "2009179",
        "fullAddress": "7 Mikoikoi Crescent, Māngere Bridge, Auckland",
        "streetName": "Mikoikoi Crescent",
        "streetNumber": "7",
        "coordinates": [
          -36.9498299,
          174.7925922
        ]
      }
    ]
  },
  {
    "precinctId": "kaihua-terrace",
    "name": "Kaihua Terrace",
    "count": 7,
    "addresses": [
      {
        "id": "2009178",
        "fullAddress": "1 Kaihua Terrace, Māngere Bridge, Auckland",
        "streetName": "Kaihua Terrace",
        "streetNumber": "1",
        "coordinates": [
          -36.9497038167,
          174.79254985
        ]
      },
      {
        "id": "2037228",
        "fullAddress": "11 Kaihua Terrace, Māngere Bridge, Auckland",
        "streetName": "Kaihua Terrace",
        "streetNumber": "11",
        "coordinates": [
          -36.9495484288,
          174.7929129884
        ]
      },
      {
        "id": "2037229",
        "fullAddress": "13 Kaihua Terrace, Māngere Bridge, Auckland",
        "streetName": "Kaihua Terrace",
        "streetNumber": "13",
        "coordinates": [
          -36.9495313883,
          174.7929854104
        ]
      },
      {
        "id": "2009177",
        "fullAddress": "3 Kaihua Terrace, Māngere Bridge, Auckland",
        "streetName": "Kaihua Terrace",
        "streetNumber": "3",
        "coordinates": [
          -36.9496840333,
          174.7926606
        ]
      },
      {
        "id": "2037225",
        "fullAddress": "5 Kaihua Terrace, Māngere Bridge, Auckland",
        "streetName": "Kaihua Terrace",
        "streetNumber": "5",
        "coordinates": [
          -36.9496038103,
          174.7927234132
        ]
      },
      {
        "id": "2037226",
        "fullAddress": "7 Kaihua Terrace, Māngere Bridge, Auckland",
        "streetName": "Kaihua Terrace",
        "streetNumber": "7",
        "coordinates": [
          -36.9495867698,
          174.7927851849
        ]
      },
      {
        "id": "2037227",
        "fullAddress": "9 Kaihua Terrace, Māngere Bridge, Auckland",
        "streetName": "Kaihua Terrace",
        "streetNumber": "9",
        "coordinates": [
          -36.9495718594,
          174.7928576069
        ]
      }
    ]
  },
  {
    "precinctId": "patiti-parade",
    "name": "Patiti Parade",
    "count": 5,
    "addresses": [
      {
        "id": "2138332",
        "fullAddress": "10 Patiti Parade, Māngere Bridge, Auckland",
        "streetName": "Patiti Parade",
        "streetNumber": "10",
        "coordinates": [
          -36.9497280239,
          174.7932369493
        ]
      },
      {
        "id": "2138331",
        "fullAddress": "12 Patiti Parade, Māngere Bridge, Auckland",
        "streetName": "Patiti Parade",
        "streetNumber": "12",
        "coordinates": [
          -36.9497883376,
          174.7932598684
        ]
      },
      {
        "id": "2037224",
        "fullAddress": "14 Patiti Parade, Māngere Bridge, Auckland",
        "streetName": "Patiti Parade",
        "streetNumber": "14",
        "coordinates": [
          -36.9498534763,
          174.7932815814
        ]
      },
      {
        "id": "2037223",
        "fullAddress": "16 Patiti Parade, Māngere Bridge, Auckland",
        "streetName": "Patiti Parade",
        "streetNumber": "16",
        "coordinates": [
          -36.9499174087,
          174.7933032943
        ]
      },
      {
        "id": "2037222",
        "fullAddress": "18 Patiti Parade, Māngere Bridge, Auckland",
        "streetName": "Patiti Parade",
        "streetNumber": "18",
        "coordinates": [
          -36.9499837537,
          174.7933298323
        ]
      }
    ]
  }
];
